name: Deploy Camunda BPMN

on:
  push:
    branches:
      - development

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy BPMN/DMN to Camunda
        run: |
          curl -X POST https://api.cloud.camunda.io/v1/deployments \
          -H "Authorization: Bearer ${{ secrets.CAMUNDA_API_TOKEN }}" \
          -H "Content-Type: multipart/form-data" \
          -F "files=@QC flow.bpmn.bpmn" \
          -F "files=@Determine required QCs.dmn" \
          -F "deploymentName=MyProcessDeployment" \
          -F "targetNamespace=your-namespace" \
          -F "tenantId=your-tenant"
