name: Deploy Camunda BPMN

on:
  push:
    branches:
      - development

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy BPMN/DMN to Camunda
        run: |
          curl -L -X POST 'https://sin-1.zeebe.camunda.io:443/0a279923-7c33-4528-ac44-5f3673406126/v2/deployments' \
            -H 'Content-Type: multipart/form-data' \
            -H 'Accept: application/json' \
            -H 'Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IlFVVXdPVFpDUTBVM01qZEVRME0wTkRFelJrUkJORFk0T0RZeE1FRTBSa1pFUlVWRVF6bERNZyJ9.eyJodHRwczovL2NhbXVuZGEuY29tL2NsdXN0ZXJJZCI6IjBhMjc5OTIzLTdjMzMtNDUyOC1h'
